### PR TITLE
Use `flutter test` in CI

### PR DESCRIPTION
**Pull request by temeddix**
This PR fixes CI to allow #77 to be merged into the main branch.

Thank you always for the amazing toolchain, and `native_toolchain_rust` you're working on also looks amazing :)

### CODE REVIEW

**Comment by knopp** [comment]
Hi, can you pin the dependency to a particular revision? 

https://docs.github.com/en/actions/security-for-github-actions/security-guides/security-hardening-for-github-actions#using-third-party-actions

**Comment by temeddix** [comment]
Sure, I've updated the PR.

**Comment by temeddix** [comment]
Hi, may I ask when this PR would be reviewed? I would be happy to make further changes if there should be any.

**Comment by knopp** [comment]
Sorry from the delay, this slipped my radar.

**Pull request merged**
